/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppRoot {}
  interface CalendarComponent {}
  interface DailyTaskInsertEdit {
    'match': MatchResults;
  }
  interface DailyTaskList {}
  interface HeaderComponent {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCalendarComponentElement extends Components.CalendarComponent, HTMLStencilElement {}
  var HTMLCalendarComponentElement: {
    prototype: HTMLCalendarComponentElement;
    new (): HTMLCalendarComponentElement;
  };

  interface HTMLDailyTaskInsertEditElement extends Components.DailyTaskInsertEdit, HTMLStencilElement {}
  var HTMLDailyTaskInsertEditElement: {
    prototype: HTMLDailyTaskInsertEditElement;
    new (): HTMLDailyTaskInsertEditElement;
  };

  interface HTMLDailyTaskListElement extends Components.DailyTaskList, HTMLStencilElement {}
  var HTMLDailyTaskListElement: {
    prototype: HTMLDailyTaskListElement;
    new (): HTMLDailyTaskListElement;
  };

  interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {}
  var HTMLHeaderComponentElement: {
    prototype: HTMLHeaderComponentElement;
    new (): HTMLHeaderComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'calendar-component': HTMLCalendarComponentElement;
    'daily-task-insert-edit': HTMLDailyTaskInsertEditElement;
    'daily-task-list': HTMLDailyTaskListElement;
    'header-component': HTMLHeaderComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface CalendarComponent {}
  interface DailyTaskInsertEdit {
    'match'?: MatchResults;
  }
  interface DailyTaskList {}
  interface HeaderComponent {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'calendar-component': CalendarComponent;
    'daily-task-insert-edit': DailyTaskInsertEdit;
    'daily-task-list': DailyTaskList;
    'header-component': HeaderComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'calendar-component': LocalJSX.CalendarComponent & JSXBase.HTMLAttributes<HTMLCalendarComponentElement>;
      'daily-task-insert-edit': LocalJSX.DailyTaskInsertEdit & JSXBase.HTMLAttributes<HTMLDailyTaskInsertEditElement>;
      'daily-task-list': LocalJSX.DailyTaskList & JSXBase.HTMLAttributes<HTMLDailyTaskListElement>;
      'header-component': LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
    }
  }
}


